version: '2'

networks:
  dev_net:
    external: true

services:
  monitoring:
    container_name: blockchain-monitoring
    image: blockchainmonitoring/blockchain-monitoring:latest
    volumes:
      - $FABRIC_NET_CONFIG:/etc/conf/net-config.yaml
    ports:
      - "3000:3000"
      - "8086:8086"
    networks:
      dev_net:
        ipv4_address: 172.25.0.135
