version: '2'

networks:
  dev_net:
    external: true

services:
  monitoring:
    container_name: monitoring
    image: fabricmonitoring/fabric-monitoring:1.0.0
    volumes:
      - $FABRIC_NET_CONFIG:/etc/conf/net-config.yaml
    ports:
      - "3000:3000"
    networks:
      - dev_net
