organisations:
- name: 'organisation-1'
  ca:
    name: 'ca-organisation-1'
    address: 'http://localhost:7054'
  enroll:
    login: 'admin-organisation-1'
    pass: 'admin'
    msp: 'organisation-1'
  peers:
    - name: 'peer-1'
      address: 'grpc://peer-1:5051'

    - name: 'peer-2'
      address: 'grpc://peer-2:6051'

    - name: 'peer-3'
      address: 'grpc://peer-3:7051'

- name: 'organisation-02'
  ca:
    name: 'ca-organisation-02'
    address: 'http://ca-organisation-02:7054'
  enroll:
    login: 'admin-organisation-02'
    pass: 'admin'
    msp: 'organisation-02'
  peers:
    - name: 'peer-organisation-02'
      address: 'grpc://peer-4:8051'
